test_suites:
    - name: e2e
      script_path: /root/okta/samples-nodejs-express-4/scripts
      sort_order: '1'
      timeout: '10'
      script_name: e2e
      criteria: MERGE
      queue_name: small
